### ISSUE TITLE
Found a possibile CPU leak

### ISSUE THREAD

**Issue by SamuelPozzobon** [meyfa/CobolCraft#224]
Hello,
I have recently discovered a potential CPU leak when a player is continuously refreshing the server list.

https://github.com/user-attachments/assets/0e940d29-14a9-4d99-988a-0cfdec3a4f75

The console is also returning the following error:
[client=0000000001] Timeout
[client=0000000002] Timeout
[client=0000000003] Timeout

**Comment by meyfa** [comment]
Nice catch. I was able to reproduce this on my machine. However, I couldn't click Refresh fast enough and had to hold down F5 for a while before it suddenly happened.

I'm not sure what causes this, but the CPU went back to idle after a few seconds, so I don't think this is a big problem.

**Comment by meyfa** [comment]
I rewrote the network stack (#230, #231, #232) to improve performance, and while this can still be reproduced, the sockets are now handled more efficiently and at least in my testing the CPU usage drops back down much more quickly now. Also, this is basically a DoS attack, so I guess some performance impact is expected.

I'll go ahead and close this, but feel free to re-open if you disagree and we can discuss solutions.

**Comment by GitMensch** [comment]
If you can still reproduce it by holding F5, then this would be a very nice option to use `perf record -p $(pgrep cobolcraft)` (you can also start the recording for the process via hotspot) before pressing F5 and keeping it pressed, then stop the recording shortly after the CPU went down again.

I'd be interested to see where the performance is (and how this changes between GC 3.2 and 3.3, if any).
Again I _guess_ there will be possible optimizations on both libcob/codegen and COBOL side.

Maybe reopen for the perf analysis?

**Comment by GitMensch** [comment]
ping @meyfa - as that potentially can be closed relative easily

**Comment by meyfa** [comment]
I'll work on this once it's the most interesting thing on the to-do list. :)
