### ISSUE TITLE
Congrats on using COBOL

### ISSUE THREAD

**Issue by russurquhart1** [meyfa/CobolCraft#233]
Hi,
I learned COBOL back in college MANY years ago! I had a really good teacher and learned it very well, IMO. So much so, that the next semester, for my Data Structures class, i used COBOL for the data structures assignments as I was able to call an IBM graphics interface, and present the data structures in this manner. It was fun and my teacher gave me extra credit for it!

Keep up the good work with COBOL!

Russ

**Comment by meyfa** [comment]
Thanks, glad you like it!
